# Generated by Django 5.2.14 on 2026-06-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_type',
            field=models.CharField(choices=[('solo', 'Solo'), ('collab', 'Collaboration')], default='solo', max_length=10),
        ),
    ]
