# Generated by Django 5.2.14 on 2026-06-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_jamsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jamsession',
            name='session_id',
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_status',
            field=models.CharField(choices=[('none', 'ยังไม่อัปโหลด'), ('pending', 'กำลังรอคิวอัปโหลด'), ('completed', 'อัปโหลดเสร็จสิ้น'), ('failed', 'อัปโหลดล้มเหลว')], default='none', max_length=20),
        ),
    ]
