# Generated by Django 5.2.14 on 2026-06-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_remove_jamsession_session_id_video_youtube_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='youtube_status',
            field=models.CharField(choices=[('none', 'ยังไม่อัปโหลด'), ('pending', 'กำลังรอคิวอัปโหลด'), ('uploading', 'กำลังอัปโหลด...'), ('completed', 'อัปโหลดเสร็จสิ้น'), ('failed', 'อัปโหลดล้มเหลว')], default='none', max_length=20),
        ),
    ]
