# Generated by Django 5.2.14 on 2026-06-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_alter_video_youtube_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='fuzik_url',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
